
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: lifebit-app
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: lifebit-app
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 40