name: Setup Infra

on:
  pull_request:
    types: [opened, reopened, synchronize]
  
jobs:
  build-deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
    
      - name: Terraform Workflow
        working-directory: ./Terraform-infra
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve
  