name: Setup EKS

on:
  push:
    branches:
      - "lifebit"
  
jobs:
  build-deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
    
      - name: Terraform Workflow
        run: |
          terraform init
          terraform plan
          terraform apply --auto-approve
  